### ISSUE TITLE
Link zum gitbook

### ISSUE THREAD

**Issue by staabm** [redaxo/dokumentation#3]
Unter http://www.redaxo.org/de/doku/ gibt es noch keine hinweise/links zur r5 doku/gitbook

**Comment by staabm** [comment]
//cc @polarpixel

**Comment by polarpixel** [comment]
Danke für den Hinweis.
Ich habe eine Seite mit Links und ein paar Hinweisen angelegt.
http://www.redaxo.org/de/doku/version-5/
