### ISSUE TITLE
Q&A: Wie erstelle und nutze ich eine 2. Datenbank-Verbindung?

### ISSUE THREAD

**Issue by alexplusde** [redaxo/dokumentation#7]
# Antwort
In der config.yml eine 2. Datenbank angeben. 

## In Modulen / Templates 
`$sql = rex_sql::factory(2);` verwenden.

## In SQL-Queries (bspw. in Meta-Infos, YForm)
`(DB2) SELECT * FROM ...`

## Link zur API-Dokumentation
http://www.redaxo.org/docs/master/class-rex_sql.html

**Comment by gharlan** [comment]
> `$sql = new sql(2);`

`$sql = rex_sql::factory(2);` ;)

Und schon mal noch einen anderen Tipp: Es gibt verschiedene Stellen, wo man Queries in dieser Form schreiben kann:
`(DB2) SELECT * FROM ...`
Insbesondere wären da die Metainfos zu nennen. Zum Beispiel kann man ein Selectfeld als Metainfo erstellen, wo die Optionen per Query aus der 2. DB abgefragt werden.

**Comment by gharlan** [comment]
Hinter dieser Notation steckt übrigens diese Methode: `$sql->setDbQuery()` (als Erweiterung von `setQuery()`).

**Comment by alexplusde** [comment]
@gharlan du bist ein wandelndes Redaxo-Lexikon. :) 👍

**Comment by alexplusde** [comment]
Sorry, war die falsche Repo. Hier geht's weiter. https://github.com/redaxo/docs/issues/1
